### ISSUE TITLE
Have the Linux Flatpak Associate C# Files

### ISSUE THREAD

**Issue by define-private-public** [mono/monodevelop#3569]
I'm running Ubuntu 17.10 at the moment, and this system has MonoDevelop installed using the Flatpak method.  While this isn't not hampering my ability to use the IDE, it's a little frustrating.  Files with extensions such as `.sln`, `.csproj`, `.cs` Don't seem to open up MonoDevelop when I click on them.  This was the default behavior in the apt version of MonoDevelop.

**Comment by directhex** [comment]
MimeType info is (seemingly) correctly exported, but isn't being made use of by the parent OS. I'm discussing w/ the Flatpak developers.

**Comment by directhex** [comment]
OK, I've dispatched a build with a proposed workaround to the issue https://github.com/mono/monodevelop-flatpak/commit/ffa38cd59200ae5220b6f5437cf31d841f9a8620

**Comment by define-private-public** [comment]
Okay, I can't take a look at it until about 5 PM EST today, but I'll try it then.

**Comment by directhex** [comment]
Conveniently, that's about how long it takes to build

**Comment by directhex** [comment]
```
$ gio info Gtk2Test.sln | grep standard::content-type
  standard::content-type: application/x-sln
```

New MIME types are being correctly exported & associated with the relevant file extensions (and the MIME association with MonoDevelop works)

**Comment by define-private-public** [comment]
I tried updating today.  When first updating, the `.sln` files still weren't being opened by MonoDevelop by default.  I tried uninstalling it and installing it again.  No luck.  when I did the `Right Click -> Properties -> Open With` and set it to `MonoDevelop`, it will now open the file with MonoDevelop by default.

Though the Icons don't have any MonoDevelop branding on them (looks like a plaintext file).  Also checking the `gio info` returned this:

```
ben@machine:Gtk2Test$ gio info Gtk2Test | grep content-type
  standard::content-type: inode/directory
  standard::fast-content-type: inode/directory
ben@machine:Gtk2Test$ 
```

**Comment by directhex** [comment]
> Though the Icons don't have any MonoDevelop branding on them (looks like a plaintext file). 

That's between you & your icon theme. MonoDevelop doesn't bundle its own icons for these file types - and the default theme on GNOME 3 (Adwaita) doesn't include one.

![adwaita](https://user-images.githubusercontent.com/308992/34678895-6cab741a-f462-11e7-8371-068826c603a2.png)
![elementary](https://user-images.githubusercontent.com/308992/34678896-6cb5200a-f462-11e7-8995-14ba2b66e326.png)
![faenza](https://user-images.githubusercontent.com/308992/34678897-6cc21602-f462-11e7-8180-ea7239243890.png)
![numix](https://user-images.githubusercontent.com/308992/34678898-6ccafc54-f462-11e7-90cf-09696599c45a.png)

> Also checking the gio info returned this

Well, yes, you ran it on a directory, so that seems correct to me
