### ISSUE TITLE
Cannot P/Invoke libraries outside the sandbox

### ISSUE THREAD

**Issue by define-private-public** [mono/monodevelop#3573]
At the moment I'm working on a project that needs to interface with `libgphoto2`, thus I'm creating a C# wrapper for it.  All of my P/Invoke'd functions use the attribute like this:

```c#
[DllImport("gphoto2")]
private static extern int gp_camera_new(ref IntPtr camera);
```

When using MonoDevelop packaged with Flatpak, it's throwing a `System.DllNotFoundException` for `gphoto2`.  I'm running Ubuntu 17.10, and have the `gphoto2` and `libgphoto2-dev` packages installed.  If I go to where the build .exe lives (i.e. `Project/bin/Debug/`) and run the executable using `mono` from the `mono-runtime` package, my program works as expected.

I grabbed a machine that is similarly configured to the one described above, but it's not using MonoDevelop inside a Flatpak, and it's having no issues. I'm assuming that this stems from the nature that Flatpaks are supposed to be self contained. This really hampers me if I can't Debug my applications now because of how MonoDevelop is distributed.

**Comment by Therzok** [comment]
@define-private-public I suppose this is because `LD_LIBRARY_PATH` is not inherited by the `MonoDevelop` application. The terminal inherits it, while the self contained flatpak might not.

As a workaround, you could try setting the environment variable to point to where `gphoto2` is installed when debugging via `Project Options -> Run Configurations -> Environment Variables`.

cc @directhex on how to inherit env vars like that from the system.

**Comment by directhex** [comment]
Right now there's no workaround. I'm actively working on this scenario.

**Comment by define-private-public** [comment]
Okay, thanks for taking a look into this.  You might want to attach the `High Priority` label to this, because P/Invoke is a semi-critical, and it really sucks if no one can develop a C# app that requires that feature.
