### ISSUE TITLE
build fails on ubuntu if MONO_IOMAP=all not set

### ISSUE THREAD

**Issue by germgerm** [mono/monodevelop#3691]
Building from source on ubuntu requires MONO_IOMAP=all to be set
If it isn't the build fails with the following error :
```
"~/monodevelop/main/Main.sln" (default target) (1) ->
"~/monodevelop/main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj" (default target) (86) ->
(BeforeBuild target) -> 
  ~/monodevelop/main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj(68,5): error MSB3030: Could not copy the file "../packages/FSharp.Core/FSharp.Core.4.1.0.2.nupkg" because it was not found.
```
The specified .nupkg definitely does exist.
I have confirmed this across multiple fresh os installs - ubuntu 16.04 lubuntu 17.10 xubuntu 17.10
This conflicts with issue #3542 -> package manager fails if MONO_IOMAP=all is set.

Further testing - this seems to have been resolved since the last release - problem as described exists at 7.4.0.839 - current builds fine but crashes after opening a solution - possibly related to #3533 but hitting different error - see #3693

**Comment by atsushieno** [comment]
One of the typical cause of this problem is that there are local package cache directories like "FSharp.Core" and "fsharp.core" . That could happen if you used to run old monodevelop that does not lowercase package cache directory.

Now monodevelop tries to look up package directory in case insensitive manner and still finds FSharp.Core (before fsharp.core) and treats it as the package directory, then the expected assembly might not be found. Your case looked like this pattern because it says: `Could not copy the file "../packages/FSharp.Core/FSharp.Core.4.1.0.2.nupkg" because it was not found.` (note the directory name)

That could be found only when monodevelop leaves build processing to MSBuild, and if that's the case it's not easy to find that kind of defects.

One possible solution would be to detect those conflicting directories when resolving package directory and remove non-lowercase one.

**Comment by germgerm** [comment]
Thanks - this is happening on fresh installs - so the only existing packages are those installed by the MD build - unless mono-complete or mono-xsp4 installs packages as well.  nuget cache directories are all lowercase, solution package directories are mixed case.
I will check to see if any unexpected directories exist

**Comment by nosami** [comment]
@mrward @germgerm Yes, this is precisely what was fixed.

**Comment by germgerm** [comment]
Can confirm that current master successfully builds without MONO_IOMAP being defined.  However, it crashes after opening a solution. - for now will stick with 7.4[.0.839] - requires MONO_IOMAP to build but it doesn't crash
