### ISSUE TITLE
C# debugging operation is silently ignored if you point to non-existent directory to run

### ISSUE THREAD

**Issue by atsushieno** [mono/monodevelop#3697]
We are all stupid and sometimes we point to non-existent directory at "Run in directory" in the project configuration in your C# project. Then you hit F5 and expect that the debugger starts, but it doesn't. And we have no idea why it doesn't launch. Especially when you see "Debug Application" operation works.

It would be nice if monodevelop alerts that the directory does not exist.

Testing environment:

- Ubuntu 16.04.
- monodevelop e9cbc2676

> VS bug #569970

**Comment by atsushieno** [comment]
Repro steps:

- Create some C# project
- In the project configuration, go to "Run" -> "Configurations" -> "Default" and specify some non-existent directory at "Run in directory" column.
- Start debugging.

**Comment by atsushieno** [comment]
Forgot to mention: it is not only about debugging, but also simple execution without debugging.

**Comment by atsushieno** [comment]
Is @xamarin-release-manager buggy and closing issues randomly?

**Comment by Daniel-McCarthy** [comment]
Would it be possible to be pointed in the right direction for this Issue?
___
I started by finding where this "Run in directory" option is used in the code base so that a check could be done to see if the folder exists. I found the `StartWorkingDirectory` property which is in the `AssemblyRunConfiguration`.

From there I saw that an `AssemblyRunConfiguration` object is used in the class `DotNetProject`, specifically the `OnGetCanExecute`. However, that function is getting called repeatedly and seems to control whether or not the Start Debugging/Start Without Debugging options are enabled.

This did not seem like the optimal place to alert the user to this issue since it is called and checked repeatedly. So I then found where the code that relates to Start Debugging and Start Without Debugging. I located the `Run` function in `ProjectCommands` and `DebugCommands` and followed the functions that are executed from there down.

However, while this seemed like the perfect place to check and alert the user that the folder does not exist, I can not seem to find where this  run-in-folder/`StartWorkingDirectory` property is used in this section of the code base.
___
I was hoping either I might be able to get a pointer on how to continue from here (or that at least that some of what I tried and looked into might be useful for other people interested in contributing).

**Comment by DavidKarlas** [comment]
Hi Dan,

you were very close by looking at `OnGetCanExecute`. I think change should be made in `OnExecuteCommand` command in same class. Once `executionCommand` is casted into `dotNetExecutionCommand` there is `WorkingDirectory` property on that field.
And here is example how to report a problem and abort execution https://github.com/mono/monodevelop/blob/040f3b24c7f9d7256f5d475230350bf6ef75dcb8/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs#L1902-L1903

Hopefully this will help you.

Btw, that `WorkingDirectory` property is set from `StartWorkingDirectory` here: https://github.com/mono/monodevelop/blob/040f3b24c7f9d7256f5d475230350bf6ef75dcb8/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs#L1441

Regards,
David

**Comment by Daniel-McCarthy** [comment]
That is wonderful information! @DavidKarlas Thank you very much for the help. That is exactly what I needed. I am glad I was able to get somewhat on the right track. Thanks for taking the time to help point me in the right direction and share this information!

I hope to make a pull request for this soon.

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.1372 (master)

Author: Dan McCarthy
Commit: 5f9a7806d7eafc91008bef6f5129803ce83d62d0 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-27] Comment by **xamarinc**



Fixed in version 8.0.0.1372 (master)



Author: Dan McCarthy  
 Commit: 5f9a7806d7eafc91008bef6f5129803ce83d62d0 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-28] Comment by **xamarinc**



Fixed in version 8.0.0.2001 (release-8.0)



Author: Dan McCarthy  
 Commit: 5f9a7806d7eafc91008bef6f5129803ce83d62d0 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-31] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Dan McCarthy  
 Commit: 5f9a7806d7eafc91008bef6f5129803ce83d62d0 (xamarin/monodevelop)
