### ISSUE TITLE
GetSemanticModelAsync should not be called from UI Thread

### ISSUE THREAD

**Issue by DavidKarlas** [mono/monodevelop#3770]
https://github.com/mono/monodevelop/blob/ddb4355/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RoslynClassificationHighlighting.cs#L137

Found this issue via UIThread hangs monitor...

> VS bug #569967

**Comment by mkrueger** [comment]
It's not called from ui thread - it's called async with await. I'm not sure if the hangs monitor is the issue here.

**Comment by DavidKarlas** [comment]
It is called from UI thread from gtk `OnExposeEvent` method:
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/774791/36531554-992fa928-17be-11e8-8898-338ad621282d.png">

Even if it's called with `await`, there is no guarantee(or even promise) it won't execute on same thread.

**Comment by mkrueger** [comment]
It's executed on the same thread when the semantic model is up2date and cached.
Creating always a task would be too much overhead. I'll discuss that with the roslyn guys.

**Comment by mkrueger** [comment]
We call it always on UI thread like that - if that it would be a problem we would block all the time. So I doubt it's an issue.

**Comment by mkrueger** [comment]
ATM I don't see a way to fix that - and no issue here. If you think you can improve that - try it out. 
IMO it would just cause redraw flickers and not improve the UI in any way. That call can't block the UI thread and the semantic info is needed for the classifications since the roslyn classifiers are not 2 step like our old system was :(.

**Comment by DavidKarlas** [comment]
This was fixed with https://github.com/mono/monodevelop/pull/4740
