### ISSUE TITLE
[StaticRegistrar] Get rid of duplicate symbols in memory from statically and dynamically linking libxammac

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#3924]
Currently, we have the following scenarios:
* Debug from IDE - We don't use the stub launcher, thus we need to dynamically load libxammac.dylib
* Launcher - We use the statically linked libxammac

This forces us to load libxammac.dylib at runtime in MacPlatform. We need to figure a way to either remove loading libxammac.dylib for the debugging scenario (maybe running the stub launcher?)

Or always use libxammac.dylib in local builds, and ship with statically linked in app bundles removing the libxammac.dylib load

> VS bug #571167

**Comment by alanmcgovern** [comment]
Just to add some nuance:

We (deisgner and ios addin) depend on MonoTouch.Hosting which ships `libmthosting.dylib` which links against `libxammac.dylib`. If we ship libxammac.dylib *and* statically link it into the entry executable we break the iPhone addin and the designer because we'll have duplicate native symbols and our copy will not be initialized.

If we just remove `libxammac.dylib` from the bundle then `libmthosting.dylib` won't be loadable.

**Comment by Therzok** [comment]
End solution:
* dynamically load the static registrar at runtime

Build the static registrar as a dylib and load it

**Comment by Therzok** [comment]
Fixed via https://github.com/mono/monodevelop/pull/3918
