### ISSUE TITLE
`<Platform/>` is being remove from csproj when creating a new Project.

### ISSUE THREAD

**Issue by dellis1972** [mono/monodevelop#4040]
Context https://github.com/MonoGame/MonoGame/issues/6227

When using the new Nuget Template engine, the default `<Platform />` element is being removed from the csproj during the template creation process. 

The template [1] definitely contains values for `<Platform />` but the final project it is missing. 

Expected Result.

New csproj should contain the code for <Platform/> 

Actual Result

Its missing, as a result the project fails to compile in VSForMac.

Steps to reproduce. 

1. Install the MonoGame Extensions Addin
2. Create a MonoGame->App->MonoGame Cross Platform Desktop Application

[1] https://github.com/MonoGame/MonoGame/blob/develop/ProjectTemplates/DotNetTemplate/MonoGame.Templates.CSharp/content/BlankApp.DesktopGL/BlankApp.Desktop.csproj#L6

> VS bug #576709

**Comment by mrward** [comment]
This looks like it is fixed.

I tried VS Mac 7.3.3.5 which is affected and that seems to remove the Platform part of the .csproj file when creating a new MonoGame cross platform desktop project.

With VS Mac 7.8 the project template seems OK - it does not remove the Platform property from the start of the project.

Note that VS Mac 7.8 and 7.3.3 both complain about an invalid configuration mapping in the solution since the project template is 'Any CPU' and not 'AnyCPU' but this looks unrelated to the original problem.

My guess is that the templating engine, which was upgraded at some point after VS Mac 7.3 (maybe 7.5?), may have fixed this.
