### ISSUE TITLE
Spaces used in autoformatting - Former configuration option seems to have been removed

### ISSUE THREAD

**Issue by jkpubsrc** [mono/monodevelop#4080]
I can't configure automatic formatting of source code any more as I used to be able in earlier versions of mono develop. :-( If I have methods with argument lists that span over multiple lines, spaces are used for indentation instead of tabs in order to place arguments below the first argument of the method at character exact position.

Example:

What I encounter is this:

```
\t	\t	public void someMethod(int foo, string bar,
\t	\t	~~~~~~~~~~~~~~~~~~~~string anotherArgument)
\t	\t	{
\t	\t	\t	...
\t	\t	}
```

(Where \t refers to a tab character and ~ refers to a space character.)

What I need is this:

```
\t	\t	public void someMethod(int foo, string bar,
\t	\t	\t	string anotherArgument)
\t	\t	{
\t	\t	\t	...
\t	\t	}
```

This is annoying: I don't want to have a single space on the left hand side of any text in any line of source code files: Spaces are inconvenient to pass through. Why has the possibility of configuring this been removed? You should enable that option again, please.

**Comment by decriptor** [comment]
If I understand right because of the switch to roslyn a handful of code formatting options were lost. However, the good news is that monodevelop now supports editorconfig or at least support has been merged in (https://github.com/mono/monodevelop/pull/3616). As far as release schedule, etc I'm not sure when it'll be generally available outside of building master yourself.

**Comment by slluis** [comment]
Yes, MonoDevelop now uses Roslyn for formatting, which doesn't have this option. You can file this issue in the Roslyn repo: https://github.com/dotnet/roslyn.
