### ISSUE TITLE
F# project formatting options aren't being persisted

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#4512]
![fsharp-formatting-options](https://user-images.githubusercontent.com/667194/38611531-dc9e29e0-3d7b-11e8-9963-c07d6d08a450.gif)

Noticed in 15-7

> VS bug [#598535](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/598535)

**Comment by nosami** [comment]
Whenever I start the MonoDevelop.FSharp solution, tabs are inserted when the tab key is pressed. Both of the global preferences formatting settings and project formatting options have TabsToSpaces = true or AllowTabsAfterNonTabs=false. If I switch from Custom to Default it starts to insert spaces again, but when I restart the solution tabs start to be inserted again.

![fsharp-formatting-options-broke](https://user-images.githubusercontent.com/667194/38634717-4bb1e63e-3dbb-11e8-9511-c8f4592e5bad.gif)

**Comment by mkrueger** [comment]
That's maybe because of the .editorconfig support - I suppose it's only in monodevelop ? 

Checking the editorconfig it always sets to tab - without caring for .fs files. If that's the case it's easy - just set a .fs rule in editorconfig. And y that's by design that editor config options are always taken with priority over our policies. But that's just a guess. At least I can't repro anything like that on new f# projects.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4535 merged by: Lluis Sanchez  
 Author: mono  
 Commit: bda9e3835894722edcc801a1ace3e51c3fab1565 (xamarin/monodevelop)
