### ISSUE TITLE
Monodevelop will not save run or debug configurations

### ISSUE THREAD

**Issue by jpfreyen** [mono/monodevelop#5064]
Run -> Debug Application will NOT save the configuration I enter.
Right click, Run -> Custom Configuration will NOT save the configuration I enter either.
Most annoying , I was able to create a run configuration but I have NO way to select it...the box where it says 'Default' is greyed out.

What the heck?  This is fundamental stuff in having a good debugger.

I have monodevelop 7.4 running on Fedora 27.

**Comment by mickeyjf** [comment]
Version 7.8.4, Running on Debian 9:

Run->Run With->Custom Configuration

I have command line parameters I want to use, a default directory I'd like to run in for the sake of finding data files, and want run with the Mono Soft Debugger. None of these are defaults, and I have to re-enter them every single time I re-run my program to test some new change. Even if I could save the most recent configuration rather than selecting from several that I may have entered, that would be a huge time saver.

**Comment by mickeyjf** [comment]
Aha - I see that I can (partly) do this from the Project Option, just not from the Run With->Custom Configuration, even though these seem to use the same dialog box.

**Comment by jstedfast** [comment]
Seems like this question was resolved?

**Comment by mickeyjf** [comment]
I'd describe it more that I have found a work-around. It would still be more intuitive if the (apparently same) dialog behaved the same regardless of how you navigated to it. But that's  way down the list compared to some other things.

**Comment by jpfreyen** [comment]
I haven't been following this thread, my company moved to Jetbrains Rider.
