### ISSUE TITLE
Unsaved build output tab not visually marked as unsaved

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5147]
Unsaved build output tabs do not have the "empty circle" that indicates unsaved files

<img width="507" alt="screen shot 2018-06-21 at 1 17 12 pm" src="https://user-images.githubusercontent.com/183285/41734600-6df7de2a-7555-11e8-85ed-82355fbbf499.png">

> VS bug [#636704](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636704)

**Comment by slluis** [comment]
This is the expected behavior. The build log does not represent a file you can modify and save, it is a view of the last build result. We have a button in case the output needs to be exported to a file (maybe the button should be Export instead of Save).

**Comment by slluis** [comment]
@mhutch then the spec is wrong. Can you please elaborate why is this needed?

**Comment by rodrmoya** [comment]
In fact, I think we implemented it that way but then reverted, since it’s quite confusing:

* User opens solution and builds 
* User opens build output
* User closes solution or quits VSfM results in a dialog popping up to save the build output

We already disable/enable the save button on the document toolbar based on the status of the build output tab, so I think that should be enough?

**Comment by mhutch** [comment]
/cc @maryanne-exe

The goal was to have an intuitive transition between the current build output and viewing/saving past build logs.

* Build output opens up in a transient (preview) document tab
* The preview tab can be turned into a real (unsaved) document tab, useful for log comparisions
* The unsaved document tab can be saved, for sharing
* Saved logs can be opened up and become normal tabs

The preview tab would show the most recent log, real tabs would capture a specific log.

An alternative to this design would be to simply have a "Build Output" tab that displays the most recent log. That's not what we have. We have a weird broken hybrid, a tab that looks like a file - it has a filename in the title - and is _literally indistinguishable from a saved log tab_ aside from whether the save tab is enabled.

**Comment by slluis** [comment]
We are missing one piece of this design, which is transient tabs. Until we have that, we need a behavior that makes sense. Marking the build output document as "dirty" doesn't make sense, since it is not a document that can be modified, and the content changes every time the solution is built. We can change the document title to "Build Output" to avoid it being confused with a file.
