### ISSUE TITLE
NuGet: Adding a package from a specific source still probes all the sources

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5557]
When using the Add Packages dialog, we seem to be using all the package sources to resolve the given package.

If we're using the UI to get System.Memory 4.5.1 from nuget.org source, we should not try to probe other sources on adding.

And for some reason, it decided to install Microsoft.CodeAnalysis even though it's referenced via `$(ReferencesRoslyn)` rather than being directly included as a reference in the csproj.

https://gist.github.com/Therzok/b6c596436148015ae40c52dfeca980b6

> VS bug [#669535](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/669535)

**Comment by mrward** [comment]
All enabled sources are used when installing - this is by design. The reason for this is you could be installing a NuGet package from a MyGet feed and it depends on other packages from say nuget.org. Without using the other NuGet package sources the install would fail. Visual Studio on Windows should have the same behaviour.

What is the problem here? - System.Memory 4.5.1 was installed and what happened that was wrong?

**Comment by mrward** [comment]
You would have to disable the other enabled sources if you do not want them to be used. It did in the past just use the single package source originally but there were bugs raised for the scenario I mentioned about using MyGet. So all dependencies are resolved using all enabled sources to handle dependencies being on other sources and not on the main source.

**Comment by Therzok** [comment]
Closing, there's a different way to fix it, and it's via MSBuild specified sources.
