### ISSUE TITLE
[msbuild] Microsoft.CSharp.Core.targets was not found on Raspian 9

### ISSUE THREAD

**Issue by Int32Overflow** [mono/monodevelop#8615]
Compiling simple "Hello World" programs on a Raspberry Pi (Raspian 9) currently does not work in the currently available MonoDevelop.

**Comment by DavidAtHub** [comment]
I have the same problem on Raspbian 9，Mono and MonoDevelop is the latest version； Mono（6.0.0.327），MonoDevelop（7.6 preview build711）；

**Comment by Jeprotec** [comment]
I had the same problem with Monodevelop.
I believe I can now offer a viable solution:

It's just a setting that has to be done in Monodevelop before you start a new project:

Search under the settings, create and disable the point "create with MSBuild instead of xbuild".

After that all new projects will be recognized without errors.

For old projects the procedure is similar:
but there you should delete the folder ".vs" in the project folder first (better make a backup copy first! ;) )
Start Monodevelop. Check that the settings are as described above.
Then open the project in Monodelop.
When you open the project, it will be reinitialized and can then be edited and compiled without any problems.

**Comment by smetronic** [comment]
Hi, I cannot find the setting for "create with MSBuild instead of xbuild", can you explain the solution to this problem in detail. Thanks
