### ISSUE TITLE
monodevelop cant find Microsoft.CSharp.Core.targets on RPi4

### ISSUE THREAD

**Issue by carlpi1** [mono/monodevelop#9273]
Followed this from the monodevelop page. Please see error below. 
Found: Microsoft.CSharp.Core.targets  in Roslyn folder
Please Help

sudo apt install apt-transport-https dirmngr

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

echo "deb https://download.mono-project.com/repo/debian vs-raspbianstretch main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list

sudo apt

ERROR: update/home/pi/.cache/MonoDevelop/7.0/MSBuild/8245_1/Microsoft.CSharp.CurrentVersion.targets(5,5): Error MSB4019: The imported project "/home/pi/.cache/MonoDevelop/7.0/MSBuild/8245_1//Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. (MSB4019) (carltest1)

**Comment by carlpi1** [comment]
ERROR:

Error MSB4019: The imported project "/home/pi/.cache/MonoDevelop/7.0/MSBuild/8245_1//Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. (MSB4019)

**Comment by Jeprotec** [comment]
I had the same problem with Monodevelop under Raspian (Rasberry3)
I believe I can now offer a viable solution:

It's just a setting that has to be done in Monodevelop before you start a new project:

Search under the settings, create and disable the point "create with MSBuild instead of xbuild".

After that all new projects will be recognized without errors.

For old projects the procedure is similar:
but there you should delete the folder ".vs" in the project folder first (better make a backup copy first! ;) )
Start Monodevelop. Check that the settings are as described above.
Then open the project in Monodelop.
When you open the project, it will be reinitialized and can then be edited and compiled without any problems.
